version: "3"
services:
  nginx:
    container_name: openresty-compose
    image: mnrmano/develop:0.3
    #stdin_open: true
    tty: true
    networks:
      - frontend
    command: supervisord -c /etc/supervisor/supervisord.conf
    volumes:
      - "/var/www:/var/www"
    ports: 
      - "8080:80"
      - "50022:22"
    environment:
      TZ: Asia/Tokyo
      env: develop

  mysql:
    build: ./mysql/
    container_name: mysql-compose
    image: mnrmano/mysql:0.1
    stdin_open: true
    tty: true
    networks:
      - frontend
    restart: always
    ports:
      - "3306:3306"
    environment:
      env: develop
      TZ: Asia/Tokyo
      BIND-ADDRESS: 0.0.0.0
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: service
      MYSQL_USER: service
      MYSQL_PASSWORD: oRangeaNdaPple

networks:
  frontend:

